################################################################################
MLI_FILE		= cordova_sim_card.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-sim-card
################################################################################
